### ISSUE TITLE
[🧹 CHORE]: Upgrade google/common-protos in roadrunner-php/grpc

### ISSUE THREAD

**Issue by pfuhrmann** [roadrunner-php/issues#25]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

The new major version of google/common-protos was released in May: https://github.com/googleapis/common-protos-php/releases/tag/v4.0.0

Can we please upgrade `spiral/roadrunner-grpc` to support this version?

**Comment by butschster** [comment]
Done https://github.com/roadrunner-php/grpc/releases/tag/3.1.0
