### ISSUE TITLE
[💡 FEATURE REQUEST]: SQS Message attributes support

### ISSUE THREAD

**Issue by andrei-dascalu** [roadrunner-php/issues#26]
### Plugin

JOBS

### I have an idea!

Hi,

I'm opening an issue here because starting a discussion on https://github.com/roadrunner-php/issues/discussions leads to a 404

Basically I would like to replace using AWS SDK directly with publishing messages through RR as part of migrating closer to RR. I have this code:

```
            $result = $this->client->sendMessage([
                'DelaySeconds' => 10,
                'MessageBody' => $event->formatJson(),
                'QueueUrl' => $queueUrl,
                'MessageGroupId' => $groupId,
                'DeduplicationId' => $ddId,
            ]);
```

where `$this->client` is an instance of `Aws\Sqs\SqsClient`

I would like to do the same with RR Jobs.
Now, what I have gathered so far:

* queueUrl is not necessary since I connect to a queue via the SQS plugin (`$jobs->connect($queueName)`) as opposed to the actual URL
* SQS allows setting a delay per message for non-FIFO queues though this setting seems inherited from the queue configuration. It's fine to have a global setting in my current case, though probably some setting should be exposed on a per message level.

Issue:

Tasks as published as 

```
$a = $queue->create(SendEmailTask::class, "json body content here");
$queue->dispatch($a);
```

how can I set my deduplication id and message group id? I have my own logic for managing these and since these are per message options it would make sense that there would be a way to set them via some options or something but I haven't seen anything like this.

Is this something that exists but it's not documented yet? Is it something that should be added?

**Comment by andrei-dascalu** [comment]
Just to clarify further:
- for SQS FIFO queues these settings are per queue settings (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessage.html#SQS-SendMessage-request-MessageGroupId ) and RR jobs plugin already provides relevant configuration on a per pipeline basis
- however, for regular queues, things like delay/message group/deduplication id are per message settings - my guess is that it's up for the php jobs library to allow these to be set, right ?

**Comment by rustatian** [comment]
@andrei-dascalu 
1. `Delay` is a part of the regular JOB message from the PHP client. RR accepts this option.
2. `Message group` can be set per-pipeline. It is not a part of the JOB message. So every message sent to RR pipeline inherits the message group from it. You may create as many pipelines as you need, referring to a different [message groups](https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L1581).
3. `DeduplicationID` is a JOB ID and also accepted by the RR.

I think these aspects should be better covered in our docs (roadrunner docs I mean).

EDIT: I also updated the configuration and added the missed `message_group_id` option. You don't need to wait for a new RR version, this option already exists and handled by RR. I just missed it in the configuration `.rr.yaml`.

**Comment by andrei-dascalu** [comment]
@rustatian 

2. this is the part that doesn't work I think. Grouping is technically application logic. If one value is applied to all messages sent to a pipeline it means that all messages of a pipeline have the same group which won't work in my use case where for the same queue I need to be able to group messages on a condition that I provide (eg: in this case a message group identifier is a uuid that identifies an account that generated the event)

Is the php library currently able to perform 1 &3 ? Or is it just that RR can currently receive those settings from the PHP client but at the moment the library doesn't allow setting them?

**Comment by rustatian** [comment]
> Is the php library currently able to perform 1 &3 ? 

Yes, this is a part of the regular JOB which you send to RR.

> Grouping is technically application logic.

Makes sense. However, this is not in a conflict with my response. Your app determines when to create a pipeline and what `group` assign to it.
But, it might be more comfortable to specify a `message_group_id` with the `deduplication_id` in the JOB message and use these values instead of declared in the pipeline. If they are empty - use the values specified in the pipeline options.

**Comment by andrei-dascalu** [comment]
@rustatian Sounds good. Will the docs be updated with some examples? Right now the job creation and dispatching looks like this

```
$task = $queue->create(
  SendEmailTask::class, 
  payload: ['email' => 'dev@null.pipe']
);
```

(which it's also not correct as payload parameter is typed as `string|\Stringable`) so I'm not sure what you mean that deduplication id and message group id can currently be sent as part of the regular job (right now I see that I can specify Options with a delay - which I assume it's going to translate in the appropriate delay for SQS)

**Comment by rustatian** [comment]
@andrei-dascalu Sure, would be super cool if you would be able to send us a PR to correct that (it would be faster, since I'm not a PHP dev).

> deduplication id and message group id can currently be sent as part of the regular job

Deduplication ID is [JOB ID](https://github.com/roadrunner-server/api/blob/master/proto/jobs/v1/jobs.proto#L28) (which are messages you send to the RR).
`message_group_id` can be sent via RR's [declare RPC call](https://github.com/roadrunner-server/jobs/blob/master/rpc.go#L116C45-L116C45). It contains a hashmap with a key-value pairs to declare a pipeline (the same, which you can create via configuration).

**Comment by andrei-dascalu** [comment]
@rustatian Ok, that clears some things up.

->deduplication_id = job id in the context of SQS (would be great to emphasize this point in the docs) 
-> delay => can be set via options
-> message_group_id => this is the point that I think should be improved. In my case I need to basically dynamically declare a new pipeline whenever I send a message for a new customer. That's terribly impractical. At the moment given that we're migrating towards a better integration with RR, the messages are consumed externally (by some lambdas) but ideally we'd eventually want to have RR consumers handle that as well. If a long running process would be dynamically defining new pipelines (in itself an impractical workaround which poses some testing questions and issues), how would consuming them work?

**Comment by rustatian** [comment]
Every pipeline has its own listener which listens for the messages for the particular queue. You also have the priorities per-pipeline. The smaller number - the higher will be priority. So, you may prioritize some important messages over the non-important. Moreover, each pipeline has its own redial/reconnect mechanism, which is also good for the durability.

>  In my case I need to basically dynamically declare a new pipeline whenever I send a message for a new customer. That's terribly impractical.

Pipeline is just a logical concept to distinguish between the message groups and queues. You may declare 500–1000 pipelines (there is no limit) and that is fine for the RR.

So, after RR receives the message from the queue, it sends it to the priority queue located in the JOBS plugin. Then, all messages from the pipelines are prioritized (binary heaps) according to the priorities set in the configuration (or via declared on-the-fly args for the pipeline).
In the JOBS plugin, we have a set of pollers (threads) which are concurrently trying to get the job from the priorities queue and send it to the worker. After processing in the worker and if there are no errors - the job receives acknowledge.
You may control the retries from the worker or may say to requeue the job with the new headers. Only after a new job pushed to the queue, RR deletes it from the previous queue. So, there are no chances to lose the data.

**Comment by andrei-dascalu** [comment]
@rustatian That makes perfect sense so my take is that it's perfectly fine to declare pipelines dynamically. 
From a user perspective though in my case it still doesn't make sense to have to create a pipeline (which is largely a concept that helps with consuming messages) in order to publish a message having these options (mostly because I have to ensure the existence of a pipeline with any number of combinations of these parameters whenever I publish a message).

**Comment by rustatian** [comment]
@andrei-dascalu Please create a feature request in the `⁣roadrunner-server/roadrunner` repository about that. Since the next release is `2024.1` and we decided to do a BC for the JOBS options (protobuf), your FR might also be implemented.

**Comment by rustatian** [comment]
So basically, we need to update our JOBS payload to include all these options, especially, `message_group_id`.
