### ISSUE TITLE
[💡 FEATURE REQUEST]: gRPC Server Reflection Protocol

### ISSUE THREAD

**Issue by ALameLlama** [roadrunner-php/issues#31]
### Plugin

GRPC

### I have an idea!

I'd love to see support for the [gRPC Server Reflection Protocol](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md) added.

This is how they've done it in [node](https://github.com/grpc/grpc-node/tree/master/packages/grpc-reflection) and [go](https://github.com/grpc/grpc-go/tree/master/reflection)

**Comment by rustatian** [comment]
Hey @ALameLlama 👋 
This is the wrong organization (should be roadrunner-server/roadrunner). However: 
1. gRCP reflection server is related to Go `gRPC` plugin, not PHP.
2. There were a few attempts - 
https://github.com/roadrunner-server/grpc/pull/63
https://github.com/roadrunner-server/grpc/pull/41
https://github.com/roadrunner-server/grpc/pull/37 
to add this feature, and it works for the single-file proto. But for the complex cases like several proto files, dependencies like google protobuf (or other local deps) this case was quickly going out of the scope of a small single feature.
So, the general advice here is just to use a specific for this case tools like: Postman (and specify a proto), [grpccurl](https://github.com/fullstorydev/grpcurl), etc

EDIT: Just to explain a bit more: `gRPC` RR plugin doesn't compile, but parse the specified by the user protos. Most of the examples (99.9%) uses a simple representation like you've sent as the example. This does work with the compiled, aka: `*.pb.go` files like a charm, but as I mentioned, we're not compiling them to collect and intercept all the available methods defined in your protobuf file to pass the payloads to the PHP worker.

**Comment by ALameLlama** [comment]
@rustatian Thanks for the explanation :)
