### ISSUE TITLE
[🐛 BUG]: spiral/roadrunner-worker - Sending `null` in response header breaks serialization

### ISSUE THREAD

**Issue by FluffyDiscord** [roadrunner-php/issues#33]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Sending `null` value in a response header fails due to `null` not being able to "convert to string"

![image](https://github.com/roadrunner-php/issues/assets/10332247/8f36143d-d6b9-4ca5-b98e-f5e615020d69)

I would expect the package to strip invalid headers or at least throw a helpful exception, instead of this cryptic thing.

### Version (package version)

spiral/roadrunner-worker v3.5.0

### How to reproduce the issue?

Send back `null` in a header.

![image](https://github.com/roadrunner-php/issues/assets/10332247/c568c698-43c6-4614-9d87-9e6fb83aefbf)

**Comment by rustatian** [comment]
Hey @FluffyDiscord 👋 
Would you be able to send a PR to fix that? 🙏

**Comment by FluffyDiscord** [comment]
I guess I can try. How should it behave then, throw an exception, or strip the invalid header?

**Comment by rustatian** [comment]
@msmakouz Could you please help with the behavior here?

**Comment by msmakouz** [comment]
@FluffyDiscord Hi, it was fixed in v3.5.1. Could you please check?

**Comment by FluffyDiscord** [comment]
Can confirm its fixed, thank you.
